### ISSUE TITLE
Crash using TokuMX mongo shell v2.0.2-mongodb-2.4.10

### ISSUE THREAD

**Issue by roman-vynar** [Percona-Lab/prometheus_mongodb_exporter#30]
Creating this issue on behalf of the user https://www.percona.com/forums/questions-discussions/percona-monitoring-and-management/46287-mongodb-problem

TokuMX mongo shell v2.0.2-mongodb-2.4.10

```
goroutine 34 [running]:
panic(0x74e180, 0xc420012050)
/usr/local/go1.7.1/src/runtime/panic.go:500 +0x1a1
github.com/Percona-Lab/prometheus_mongodb_exporter/collector/mongod.(*PreloadStats).Export(0x0, 0xc4200512c0)
/mnt/workspace/pmm-client-tarball/pmm-client-1.0.5/src/github.com/Percona-Lab/prometheus_mongodb_exporter/collector/mongod/metrics.go:363 +0x38
github.com/Percona-Lab/prometheus_mongodb_exporter/collector/mongod.(*ReplStats).Export(0xc4201ce1c0, 0xc4200512c0)
/mnt/workspace/pmm-client-tarball/pmm-client-1.0.5/src/github.com/Percona-Lab/prometheus_mongodb_exporter/collector/mongod/metrics.go:352 +0x90
github.com/Percona-Lab/prometheus_mongodb_exporter/collector/mongod.(*MetricsStats).Export(0xc420195440, 0xc4200512c0)
/mnt/workspace/pmm-client-tarball/pmm-client-1.0.5/src/github.com/Percona-Lab/prometheus_mongodb_exporter/collector/mongod/metrics.go:435 +0x4c7
github.com/Percona-Lab/prometheus_mongodb_exporter/collector/mongod.(*ServerStatus).Export(0xc4200b4300, 0xc4200512c0)
/mnt/workspace/pmm-client-tarball/pmm-client-1.0.5/src/github.com/Percona-Lab/prometheus_mongodb_exporter/collector/mongod/server_status.go:116 +0x2a7
github.com/Percona-Lab/prometheus_mongodb_exporter/collector.(*MongodbCollector).collectMongod(0xc420 0d7d20, 0xc4201831e0, 0xc4200512c0)
/mnt/workspace/pmm-client-tarball/pmm-client-1.0.5/src/github.com/Percona-Lab/prometheus_mongodb_exporter/collector/mongodb_collector.go:96 +0xd4
github.com/Percona-Lab/prometheus_mongodb_exporter/collector.(*MongodbCollector).collectMongodReplSet (0xc4200d7d20, 0xc4201831e0, 0xc4200512c0)
/mnt/workspace/pmm-client-tarball/pmm-client-1.0.5/src/github.com/Percona-Lab/prometheus_mongodb_exporter/collector/mongodb_collector.go:101 +0x49
github.com/Percona-Lab/prometheus_mongodb_exporter/collector.(*MongodbCollector).Collect(0xc4200d7d20 , 0xc4200512c0)
/mnt/workspace/pmm-client-tarball/pmm-client-1.0.5/src/github.com/Percona-Lab/prometheus_mongodb_exporter/collector/mongodb_collector.go:71 +0x370
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc42019a780, 0xc4200512c0, 0x93db20, 0xc4200d7d20)
/mnt/workspace/pmm-client-tarball/pmm-client-1.0.5/src/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x63
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
/mnt/workspace/pmm-client-tarball/pmm-client-1.0.5/src/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x326
### Warning: the exporter is in beta/experimental state and field names are very
### likely to change in the future and features may change or get removed!
### See: https://github.com/Percona-Lab/prome...ngodb_exporter for updates
mongodb_exporter version: 1.0.5, git commit hash: 4651d4d535ed6c807606daf6a864338c90e06e35
Listening on 172.17.0.1:42003
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5b9bd8]
```

**Comment by dbmurphy** [comment]
This is not a supporter version of Mongo and has been EOL'd we should not support it.

**Comment by roman-vynar** [comment]
👍
